# Generated by Django 3.0.6 on 2020-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('EmployeeProj', 'PeopleOnProject')
    ]
