# Generated by Django 3.0.6 on 2020-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapi', '0004_auto_20200517_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
